name: Generate Excel from CSVs

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas xlsxwriter openpyxl

      - name: Run conversion script
        run: python csvs_to_excel.py data_tables.xlsx

      - name: Commit generated Excel
        uses: EndBug/add-and-commit@v9
        with:
          message: "Add generated data_tables.xlsx"
          add: "data_tables.xlsx"
          author_name: "github-actions[bot]"
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
          push: true
